### PR TITLE
Add React hooks rules, .prettierrc file and code refactoring

### PR DESCRIPTION
**Pull request by karagyozovLT**

### CODE REVIEW

**Comment by digitalsimboja** [comment]
You have a missing dependency `styled-components` try and install with `yarn add styled-components`

**Review by digitalsimboja — COMMENTED** [review]
For simplicity, could you try and maintain the components in `js` instead of `jsx`. I see that you tried to duplicate the components in `jsx`?

**Comment by karagyozovLT** [comment]
> For simplicity, could you try and maintain the components in `js` instead of `jsx`. I see that you tried to duplicate the components in `jsx`?

**Comment by karagyozovLT** [comment]
> For simplicity, could you try and maintain the components in `js` instead of `jsx`. I see that you tried to duplicate the components in `jsx`?

Why? I think it is better to use jsx files

**Pull request closed without merging**
